### ISSUE TITLE
Unknown Error in ConcurrentObservableCollection

### ISSUE THREAD

**Issue by PhilippElhaus** [meziantou/Meziantou.Framework#247]
Appears to be happening randomly at initialization, unable to track it down. 
Did not happen before with regular Observable Collection. 

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values. (Parameter 'arrayIndex')
  Source=System.Collections.Immutable
  StackTrace:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.CopyTo(Array array, Int32 arrayIndex)
   at System.Collections.Immutable.ImmutableList`1.System.Collections.ICollection.CopyTo(Array array, Int32 arrayIndex)
   at Meziantou.Framework.WPF.Collections.ConcurrentObservableCollection`1.System.Collections.ICollection.CopyTo(Array array, Int32 index) in /_/src/Meziantou.Framework.WPF/Collections/ConcurrentObservableCollection.cs:line 309
   at System.Collections.ArrayList.InsertRange(Int32 index, ICollection c)
   at System.Collections.ArrayList.AddRange(ICollection c)
   at System.Collections.ArrayList..ctor(ICollection c)
   at System.Windows.Data.ListCollectionView.<RefreshOverride>b__1_0()
   at MS.Internal.Data.SynchronizationInfo.AccessCollection(IEnumerable collection, Action accessMethod, Boolean writeAccess)
   at System.Windows.Data.BindingOperations.AccessCollection(IEnumerable collection, Action accessMethod, Boolean writeAccess)
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.Refresh()
   at Trading.MainWindow.<Init>b__55_10()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Trading.MainWindow.<Init>b__55_4(Object x, NotifyCollectionChangedEventArgs y)
   at Meziantou.Framework.WPF.Collections.ObservableCollectionBase`1.OnCollectionChanged(NotifyCollectionChangedEventArgs args) in /_/src/Meziantou.Framework.WPF/Collections/Internals/ObservableCollectionBase.cs:line 133
   at Meziantou.Framework.WPF.Collections.ObservableCollectionBase`1.AddItem(T item) in /_/src/Meziantou.Framework.WPF/Collections/Internals/ObservableCollectionBase.cs:line 77
   at Meziantou.Framework.WPF.Collections.DispatchedObservableCollection`1.ProcessPendingEvents() in /_/src/Meziantou.Framework.WPF/Collections/Internals/DispatchedObservableCollection.cs:line 285
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Trading.App.Main()

  This exception was originally thrown at this call stack:
    System.Collections.Immutable.Requires.FailRange(string, string)
    System.Collections.ArrayList.InsertRange(int, System.Collections.ICollection)
    System.Collections.ArrayList.AddRange(System.Collections.ICollection)
    System.Collections.ArrayList.ArrayList(System.Collections.ICollection)
    System.Windows.Data.ListCollectionView.RefreshOverride.AnonymousMethod__1_0()
    MS.Internal.Data.SynchronizationInfo.AccessCollection(System.Collections.IEnumerable, System.Action, bool)
    System.Windows.Data.BindingOperations.AccessCollection(System.Collections.IEnumerable, System.Action, bool)
    System.Windows.Data.ListCollectionView.RefreshOverride()
    System.Windows.Data.CollectionView.RefreshInternal()
    System.Windows.Data.CollectionView.Refresh()
    ...
    [Call Stack Truncated]
```

**Comment by meziantou** [comment]
Could you share the code that throw this exception? How do you use the collection?

**Comment by PhilippElhaus** [comment]
Had this just happening again. Occurs at startup, very randomly. Cannot share the exact code sadly.

```
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Specified argument was out of the range of valid values. (Parameter 'arrayIndex')
  Source=System.Collections.Immutable
  StackTrace:
   at System.Collections.Immutable.Requires.FailRange(String parameterName, String message)
   at System.Collections.Immutable.ImmutableList`1.Node.CopyTo(Array array, Int32 arrayIndex)
   at System.Collections.Immutable.ImmutableList`1.System.Collections.ICollection.CopyTo(Array array, Int32 arrayIndex)
   at Meziantou.Framework.WPF.Collections.ConcurrentObservableCollection`1.System.Collections.ICollection.CopyTo(Array array, Int32 index) in /_/src/Meziantou.Framework.WPF/Collections/ConcurrentObservableCollection.cs:line 309
   at System.Collections.ArrayList.InsertRange(Int32 index, ICollection c)
   at System.Collections.ArrayList.AddRange(ICollection c)
   at System.Collections.ArrayList..ctor(ICollection c)
   at System.Windows.Data.ListCollectionView.<RefreshOverride>b__1_0()
   at MS.Internal.Data.SynchronizationInfo.AccessCollection(IEnumerable collection, Action accessMethod, Boolean writeAccess)
   at System.Windows.Data.BindingOperations.AccessCollection(IEnumerable collection, Action accessMethod, Boolean writeAccess)
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.Refresh()
   at Trading.MainWindow.<Init>b__55_10()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at Trading.MainWindow.<Init>b__55_4(Object x, NotifyCollectionChangedEventArgs y)
   at Meziantou.Framework.WPF.Collections.ObservableCollectionBase`1.ClearItems() in /_/src/Meziantou.Framework.WPF/Collections/Internals/ObservableCollectionBase.cs:line 119
   at Meziantou.Framework.WPF.Collections.DispatchedObservableCollection`1.ProcessPendingEvents() in /_/src/Meziantou.Framework.WPF/Collections/Internals/DispatchedObservableCollection.cs:line 285
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at Trading.App.Main()

  This exception was originally thrown at this call stack:
    System.Collections.Immutable.Requires.FailRange(string, string)
    System.Collections.ArrayList.InsertRange(int, System.Collections.ICollection)
    System.Collections.ArrayList.AddRange(System.Collections.ICollection)
    System.Collections.ArrayList.ArrayList(System.Collections.ICollection)
    System.Windows.Data.ListCollectionView.RefreshOverride.AnonymousMethod__1_0()
    MS.Internal.Data.SynchronizationInfo.AccessCollection(System.Collections.IEnumerable, System.Action, bool)
    System.Windows.Data.BindingOperations.AccessCollection(System.Collections.IEnumerable, System.Action, bool)
    System.Windows.Data.ListCollectionView.RefreshOverride()
    System.Windows.Data.CollectionView.RefreshInternal()
    System.Windows.Data.CollectionView.Refresh()
    ...
    [Call Stack Truncated]
```

**Comment by meziantou** [comment]
Without more information, it will be hard to reproduce the error and fix it. One thing that may be strange is that the WPF code access the non-bindable collection. Are you sure you bound the `AsObservable` collection?
